language: python

python:
  - "2.7"
  - "3.3"

install:
  - pip install pep8 pylint
  - pip install -r requirements.txt

script:
 - find . -maxdepth 1 -name \*.py -exec pep8 {} \;
 - find . -maxdepth 1 -name \*.py -exec pylint {} \;
